default:
  golem_name: nhp.elicitation.tool
  golem_version: 0.0.0.9000
  app_prod: no
  range:
    low: 0
    high: 100
  strategies:
    hsa:
      female:
        name: Female Health Status
        label: "Health Status"
      male:
        name: Male Health Status
        label: "Health Status"
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
